/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TrustScoreTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAverageTrustScore"
      | "getLastActivityTimestamp"
      | "getTotalTrustScore"
      | "getTrustEventArrayLength"
      | "getTrustEventCount"
      | "getTrustScoreByIndex"
      | "getTrustScoreRange"
      | "getTrustStatistics"
      | "protocolId"
      | "recordTrustEvent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TrustEventRecorded" | "TrustStatisticsViewed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAverageTrustScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastActivityTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalTrustScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustEventArrayLength",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustEventCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustScoreByIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustScoreRange",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustStatistics",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordTrustEvent",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAverageTrustScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastActivityTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTrustScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustEventArrayLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustEventCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustScoreByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustScoreRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustStatistics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordTrustEvent",
    data: BytesLike
  ): Result;
}

export namespace TrustEventRecordedEvent {
  export type InputTuple = [user: AddressLike, eventCount: BigNumberish];
  export type OutputTuple = [user: string, eventCount: bigint];
  export interface OutputObject {
    user: string;
    eventCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustStatisticsViewedEvent {
  export type InputTuple = [
    user: AddressLike,
    totalEvents: BigNumberish,
    lastActivity: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    totalEvents: bigint,
    lastActivity: bigint
  ];
  export interface OutputObject {
    user: string;
    totalEvents: bigint;
    lastActivity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrustScoreTracker extends BaseContract {
  connect(runner?: ContractRunner | null): TrustScoreTracker;
  waitForDeployment(): Promise<this>;

  interface: TrustScoreTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAverageTrustScore: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getLastActivityTimestamp: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getTotalTrustScore: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getTrustEventArrayLength: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getTrustEventCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getTrustScoreByIndex: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;

  getTrustScoreRange: TypedContractMethod<
    [user: AddressLike, startIndex: BigNumberish, endIndex: BigNumberish],
    [string[]],
    "view"
  >;

  getTrustStatistics: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, boolean] & {
        eventCount: bigint;
        lastActivity: bigint;
        hasData: boolean;
      }
    ],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  recordTrustEvent: TypedContractMethod<
    [score: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAverageTrustScore"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getLastActivityTimestamp"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalTrustScore"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTrustEventArrayLength"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTrustEventCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTrustScoreByIndex"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTrustScoreRange"
  ): TypedContractMethod<
    [user: AddressLike, startIndex: BigNumberish, endIndex: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTrustStatistics"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, boolean] & {
        eventCount: bigint;
        lastActivity: bigint;
        hasData: boolean;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordTrustEvent"
  ): TypedContractMethod<
    [score: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "TrustEventRecorded"
  ): TypedContractEvent<
    TrustEventRecordedEvent.InputTuple,
    TrustEventRecordedEvent.OutputTuple,
    TrustEventRecordedEvent.OutputObject
  >;
  getEvent(
    key: "TrustStatisticsViewed"
  ): TypedContractEvent<
    TrustStatisticsViewedEvent.InputTuple,
    TrustStatisticsViewedEvent.OutputTuple,
    TrustStatisticsViewedEvent.OutputObject
  >;

  filters: {
    "TrustEventRecorded(address,uint32)": TypedContractEvent<
      TrustEventRecordedEvent.InputTuple,
      TrustEventRecordedEvent.OutputTuple,
      TrustEventRecordedEvent.OutputObject
    >;
    TrustEventRecorded: TypedContractEvent<
      TrustEventRecordedEvent.InputTuple,
      TrustEventRecordedEvent.OutputTuple,
      TrustEventRecordedEvent.OutputObject
    >;

    "TrustStatisticsViewed(address,uint32,uint32)": TypedContractEvent<
      TrustStatisticsViewedEvent.InputTuple,
      TrustStatisticsViewedEvent.OutputTuple,
      TrustStatisticsViewedEvent.OutputObject
    >;
    TrustStatisticsViewed: TypedContractEvent<
      TrustStatisticsViewedEvent.InputTuple,
      TrustStatisticsViewedEvent.OutputTuple,
      TrustStatisticsViewedEvent.OutputObject
    >;
  };
}
